### ISSUE TITLE
can't load with docker on windows

### ISSUE THREAD

**Issue by ideiudicibus** [abixen/abixen-platform#1149] opened 2017-08-01 11:23 UTC
hi all, 
I've an issue accessing to http://local.platform.abixen.com. My configuration is;
windows 8 pro
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e3

docker-compose up -d is ok, any clue?

docker_base_1                                                Exit 0                                           
docker_business-intelligence-service-postgres-database_1     Up       5432/tcp                                
docker_business-intelligence-service_1                       Up                                               
docker_configuration_1                                       Up       8888/tcp                                
docker_core-postgres-database_1                              Up       5432/tcp                                
docker_core_1                                                Up                                               
docker_discovery_1                                           Up       0.0.0.0:8761->8761/tcp                  
docker_elasticsearch_1                                       Up       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->93
docker_gateway_1                                             Up       9090/tcp                                
docker_hystrix-dashboard_1                                   Up       0.0.0.0:8989->8989/tcp                  
docker_kibana_1                                              Up       0.0.0.0:5601->5601/tcp                  
docker_load-balancer_1                                       Up       0.0.0.0:80->80/tcp, 0.0.0.0:8080->8080/t
docker_logstash_1                                            Up       0.0.0.0:12201->12201/udp, 0.0.0.0:4260->
docker_rabbitmq_1                                            Up       15671/tcp, 0.0.0.0:15672->15672/tcp, 256
docker_redis_1                                               Up       6379/tcp                                
docker_web-client_1                                          Up       8080/tcp                                
docker_web-content-service-postgres-database_1               Up       0.0.0.0:5434->5432/tcp                  
docker_web-content-service_1                                 Up                                               
docker_zipkin-web_1                                          Up       0.0.0.0:9412->9412/tcp                  
docker_zipkin_1                                              Up       8888/tcp, 0.0.0.0:9411->9411/tcp

**Comment by mariuszkumor** [comment] 2017-08-01 20:28
@ideiudicibus what is the issue?

**Comment by ideiudicibus** [comment] 2017-08-02 06:39
The http://local.platform.abixen.com/ is unreachable

**Comment by mariuszkumor** [comment] 2017-08-02 11:36
Please provide all logs.

**Comment by ideiudicibus** [comment] 2017-08-03 10:34
do you mean docker-compose logs o each service log?
Is there any "one-line-bash" command useful for that task??
how can I send you logs? 
I can ping local.platform.abixen.com 

user@asus MINGW32 ~/projects/abixen-platform/docker (master)
$ ping 192.168.99.100

Pinging 192.168.99.100 with 32 bytes of data:
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.99.100:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

user@asus MINGW32 ~/projects/abixen-platform/docker (master)
$ ping local.platform.abixen.com

Pinging local.platform.abixen.com [127.0.0.1] with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

user@asus MINGW32 ~/projects/abixen-platform/docker (master)
$

**Comment by ideiudicibus** [comment] 2017-08-03 11:14
gist with docker-compose logs 
https://gist.github.com/ideiudicibus/c6ad545a52f86b738fb293775d459d7e

**Comment by CypraxPuch** [comment] 2017-08-03 11:29
Hi Ignazio.

You have a memory issue according to your logs. Please be sure that this
isn't the cause.

insufficient memory for the Java Runtime

**Comment by ideiudicibus** [comment] 2017-08-03 12:07
Hi,
I've 5.1GB just before the docker-compose up -d, so I'm just on the edge, I think I'm stuck on this.

**Comment by mariuszkumor** [comment] 2017-08-04 06:13
@ideiudicibus can we close this iisue?

**Comment by ideiudicibus** [comment] 2017-08-04 10:09
yes

**Closed** 2017-08-04 10:12 UTC
Labels: help wanted
