### ISSUE TITLE
Error when start abixen-platform-core

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [abixen/abixen-platform#1029] opened 2017-04-17 09:51 UTC
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.springframework.boot:abixen-platform-core:jar:1.0-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.springframework.boot:abixen-platform-core:1.0-SNAPSHOT (C:\Users\benkraoua.sidahmed\abixen-platform\abixen-platform-core\pom.xml) points at com.abixen:abixen-platform instead of org.springframework.boot:spring-boot-starter-parent, please verify your project structure @ line 12, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Abixen Platform Core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:start (default-cli) @ abixen-platform-core ---
2017-04-17 10:49:38,665 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:42,123 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:42,130 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:43,104 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:43,108 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.

 :: Spring Boot ::        (v1.4.1.RELEASE)

2017-04-17 10:49:43,773 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:43,787 com.abixen.platform.core.PlatformApplication.main() INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-17 10:49:43 800 [INFO] [c=PlatformApplication] The following profiles are active: dev
2017-04-17 10:49:46 674 [WARN] [c=ConfigurationClassPostProcessor] Cannot enhance @Configuration bean definition 'refreshScope' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2017-04-17 10:49:47 689 [WARN] [c=CacheManager] One or more caches require a DiskStore but there is no diskStore element configured. Using the default disk store path of C:\Users\BENKRA~1.SID\AppData\Local\Temp\. Please explicitly configure the diskStore element in ehcache.xml.
2017-04-17 10:49:47 806 [WARN] [c=CacheConfiguration] Configuration problem for cache APPLICATION_PAGES: MaxEntriesLocalHeap equal or greater than MaxEntriesLocalDisk. This will result in useless disk storage.
2017-04-17 10:49:47 901 [WARN] [c=CacheConfiguration] Configuration problem for cache APPLICATION_LAYOUTS: MaxEntriesLocalHeap equal or greater than MaxEntriesLocalDisk. This will result in useless disk storage.
avr. 17, 2017 10:49:49 AM org.apache.catalina.core.StandardService startInternal
INFOS: Starting service Tomcat
avr. 17, 2017 10:49:49 AM org.apache.catalina.core.StandardEngine startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/8.5.5
avr. 17, 2017 10:49:49 AM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring embedded WebApplicationContext
2017-04-17 10:49:55 581 [INFO] [c=liquibase] Waiting for changelog lock....
2017-04-17 10:50:05 581 [INFO] [c=liquibase] Waiting for changelog lock....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.170 s
[INFO] Finished at: 2017-04-17T10:50:07+01:00
[INFO] Final Memory: 65M/798M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:start (default-cli) on project abixen-platform-core: Spring application did not start before the configured timeout (30000ms -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by mariuszkumor** [comment] 2017-04-17 20:41
I'm closing because a duplicate of https://github.com/abixen/abixen-platform/issues/1028

**Closed by mariuszkumor** 2017-04-17 20:41 UTC
Labels: duplicate
